### ISSUE TITLE
Shopping Cart Page Reloading

### ISSUE THREAD

**Issue by CalzaFino** [breezefront/module-breeze-klaviyo-reclaim#1]
Magento 2.4.6-p4 
Breeze 2.14.1
PHP 8.2

The Shopping Cart page keeps reloading apparently in an infinite loop. 

To recreate the issue add any product to the cart and go to “View and Edit Cart” (/checkout/cart/)

The problem stops by disabling the Klaviyo module in Magento Admin or by disabling Breeze for the URL: /checkout/cart/

Is this supposed to be happening?

**Comment by vovayatsyuk** [comment]
Hello, this commit in breeze module should fix the issue: https://github.com/breezefront/module-breeze/commit/51841cf6a5a8985c93df67040966c3ccba2843a2
